// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0CVg06Zg5RmrumR8gNGRrIqKERZWSp4',
    appId: '1:668277881841:android:263ae0b00e466078ece250',
    messagingSenderId: '668277881841',
    projectId: 'carpool-a74fd',
    storageBucket: 'carpool-a74fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZculDyMi8sd8kPoKuPzxeXIIjpZm-JA',
    appId: '1:668277881841:ios:097bcef1dd5ba09eece250',
    messagingSenderId: '668277881841',
    projectId: 'carpool-a74fd',
    storageBucket: 'carpool-a74fd.appspot.com',
    iosBundleId: 'com.example.carPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZculDyMi8sd8kPoKuPzxeXIIjpZm-JA',
    appId: '1:668277881841:ios:01c03a35e2008185ece250',
    messagingSenderId: '668277881841',
    projectId: 'carpool-a74fd',
    storageBucket: 'carpool-a74fd.appspot.com',
    iosBundleId: 'com.example.carPool.RunnerTests',
  );
}
